title: Nymeyer Carpentry
email: jesse@jdillman.com
baseurl: ""
url: ""
markdown: kramdown
permalink: /:slug/
sass:
  sass_dir: _sass
exclude: [Gemfile.lock, Gemfile, bin, webtasks]
plugins:
- jekyll-autoprefixer